-- MySQL Script generated by MySQL Workbench
-- 05/10/14 18:41:02
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hunterdowndb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hunterdowndb` ;
CREATE SCHEMA IF NOT EXISTS `hunterdowndb` DEFAULT CHARACTER SET utf8 ;
USE `hunterdowndb` ;

-- -----------------------------------------------------
-- Table `hunterdowndb`.`tipousuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hunterdowndb`.`tipousuarios` ;

CREATE TABLE IF NOT EXISTS `hunterdowndb`.`tipousuarios` (
  `idtipousuarios` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(30) NULL,
  PRIMARY KEY (`idtipousuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hunterdowndb`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hunterdowndb`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `hunterdowndb`.`usuarios` (
  `idusuarios` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idtipousuarios` BIGINT UNSIGNED NOT NULL,
  `nombre` VARCHAR(90) NOT NULL,
  `usuario` VARCHAR(30) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `passwd` VARCHAR(260) NOT NULL,
  `fecnac` DATE NOT NULL,
  `sexo` ENUM('Mujer','Hombre','Otros') NOT NULL,
  PRIMARY KEY (`idusuarios`),
  INDEX `fk_usuarios_tipousuarios_idx` (`idtipousuarios` ASC),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  CONSTRAINT `fk_usuarios_tipousuarios`
    FOREIGN KEY (`idtipousuarios`)
    REFERENCES `hunterdowndb`.`tipousuarios` (`idtipousuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hunterdowndb`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hunterdowndb`.`categorias` ;

CREATE TABLE IF NOT EXISTS `hunterdowndb`.`categorias` (
  `idcategorias` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategorias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hunterdowndb`.`temas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hunterdowndb`.`temas` ;

CREATE TABLE IF NOT EXISTS `hunterdowndb`.`temas` (
  `idtemas` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idcategorias` BIGINT UNSIGNED NOT NULL,
  `idusuarios` BIGINT UNSIGNED NOT NULL,
  `titulo` VARCHAR(150) NOT NULL,
  `temporada` TINYINT NULL DEFAULT 0,
  `sipnosis` TEXT NOT NULL,
  `ano` SMALLINT NOT NULL,
  `fechahora` DATETIME NOT NULL,
  `pagoficial` VARCHAR(250) NULL DEFAULT NULL,
  `info` VARCHAR(45) NULL DEFAULT NULL,
  `trailer` VARCHAR(250) NULL DEFAULT NULL,
  `formato` VARCHAR(45) NULL DEFAULT NULL,
  `descargas` BIGINT NULL DEFAULT 0,
  PRIMARY KEY (`idtemas`),
  INDEX `fk_temas_categorias1_idx` (`idcategorias` ASC),
  INDEX `fk_temas_usuarios1_idx` (`idusuarios` ASC),
  CONSTRAINT `fk_temas_categorias1`
    FOREIGN KEY (`idcategorias`)
    REFERENCES `hunterdowndb`.`categorias` (`idcategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_temas_usuarios1`
    FOREIGN KEY (`idusuarios`)
    REFERENCES `hunterdowndb`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hunterdowndb`.`articulos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hunterdowndb`.`articulos` ;

CREATE TABLE IF NOT EXISTS `hunterdowndb`.`articulos` (
  `idarticulos` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idtemas` BIGINT UNSIGNED NOT NULL,
  `nombre` VARCHAR(150) NOT NULL,
  `episodio` TINYINT NOT NULL,
  `fechahora` DATETIME NOT NULL,
  PRIMARY KEY (`idarticulos`),
  INDEX `fk_articulos_temas1_idx` (`idtemas` ASC),
  CONSTRAINT `fk_articulos_temas1`
    FOREIGN KEY (`idtemas`)
    REFERENCES `hunterdowndb`.`temas` (`idtemas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hunterdowndb`.`comentarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hunterdowndb`.`comentarios` ;

CREATE TABLE IF NOT EXISTS `hunterdowndb`.`comentarios` (
  `idcomentarios` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idarticulos` BIGINT UNSIGNED NOT NULL,
  `idusuarios` BIGINT UNSIGNED NOT NULL,
  `comentario` TEXT NOT NULL,
  `fechahora` DATETIME NOT NULL,
  PRIMARY KEY (`idcomentarios`),
  INDEX `fk_comentarios_articulos1_idx` (`idarticulos` ASC),
  INDEX `fk_comentarios_usuarios1_idx` (`idusuarios` ASC),
  CONSTRAINT `fk_comentarios_articulos1`
    FOREIGN KEY (`idarticulos`)
    REFERENCES `hunterdowndb`.`articulos` (`idarticulos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentarios_usuarios1`
    FOREIGN KEY (`idusuarios`)
    REFERENCES `hunterdowndb`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hunterdowndb`.`puntajes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hunterdowndb`.`puntajes` ;

CREATE TABLE IF NOT EXISTS `hunterdowndb`.`puntajes` (
  `idpuntajes` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idtemas` BIGINT UNSIGNED NOT NULL,
  `puntaje` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idpuntajes`),
  INDEX `fk_puntajes_temas1_idx` (`idtemas` ASC),
  CONSTRAINT `fk_puntajes_temas1`
    FOREIGN KEY (`idtemas`)
    REFERENCES `hunterdowndb`.`temas` (`idtemas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hunterdowndb`.`generos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hunterdowndb`.`generos` ;

CREATE TABLE IF NOT EXISTS `hunterdowndb`.`generos` (
  `idgeneros` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idgeneros`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hunterdowndb`.`servidores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hunterdowndb`.`servidores` ;

CREATE TABLE IF NOT EXISTS `hunterdowndb`.`servidores` (
  `idservidores` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `logo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idservidores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hunterdowndb`.`urls`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hunterdowndb`.`urls` ;

CREATE TABLE IF NOT EXISTS `hunterdowndb`.`urls` (
  `idurls` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idarticulos` BIGINT UNSIGNED NOT NULL,
  `idservidores` BIGINT UNSIGNED NOT NULL,
  `url` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idurls`),
  INDEX `fk_urls_articulos1_idx` (`idarticulos` ASC),
  INDEX `fk_urls_servidores1_idx` (`idservidores` ASC),
  CONSTRAINT `fk_urls_articulos1`
    FOREIGN KEY (`idarticulos`)
    REFERENCES `hunterdowndb`.`articulos` (`idarticulos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_urls_servidores1`
    FOREIGN KEY (`idservidores`)
    REFERENCES `hunterdowndb`.`servidores` (`idservidores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hunterdowndb`.`generostemas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hunterdowndb`.`generostemas` ;

CREATE TABLE IF NOT EXISTS `hunterdowndb`.`generostemas` (
  `idgenerostemas` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idgeneros` BIGINT UNSIGNED NOT NULL,
  `idtemas` BIGINT UNSIGNED NOT NULL,
  INDEX `fk_generos_has_temas_temas1_idx` (`idtemas` ASC),
  INDEX `fk_generos_has_temas_generos1_idx` (`idgeneros` ASC),
  PRIMARY KEY (`idgenerostemas`),
  CONSTRAINT `fk_generos_has_temas_generos1`
    FOREIGN KEY (`idgeneros`)
    REFERENCES `hunterdowndb`.`generos` (`idgeneros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_generos_has_temas_temas1`
    FOREIGN KEY (`idtemas`)
    REFERENCES `hunterdowndb`.`temas` (`idtemas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
